package:
  name: llama-server
  version: 0.0.1

source:
  path: ..

build:
  number: 0
  entry_points:
    - llama-server = llama_server.server:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - click
    - fastapi
    - pip
    - pyllamacpp
    - python
    - sse-starlette
    - uvicorn[standard]
  run:
    - click
    - fastapi
    - pyllamacpp
    - python
    - sse-starlette
    - uvicorn[standard]

test:
  imports:
    - llama_server
    - llama_server.prompts
  commands:
    - llama-server --help

about:
  home: "https://github.com/nuance1979/llama-server"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "LLaMA Server combines the power of LLaMA C++ with the beauty of Chatbot UI."
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - nuance1979
