name: Conda

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_conda:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.platform }}
    # The setup-miniconda action needs this to activate miniconda
    defaults:
      run:
        shell: "bash -l {0}"
    steps:
      - uses: actions/checkout@v3
      - name: Get conda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: strict
      - name: Prepare
        run: conda install conda-build conda-verify
      - name: Build
        run: conda build .conda
      - name: Install
        run: conda install -c ${CONDA_PREFIX}/conda-bld/ llama-server
